// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4f0bQIt7Ex3-nZ_dtwA9LzcRgpx4il1M',
    appId: '1:586525703658:web:4362c0eb230a857b96c693',
    messagingSenderId: '586525703658',
    projectId: 'gezayo-2179c',
    authDomain: 'gezayo-2179c.firebaseapp.com',
    storageBucket: 'gezayo-2179c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbyNh7NF0XTcpwrsF6YKtAYZq_l7pQ2NE',
    appId: '1:586525703658:android:34689bce1e46f23596c693',
    messagingSenderId: '586525703658',
    projectId: 'gezayo-2179c',
    storageBucket: 'gezayo-2179c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAY1JFJMDR0ib9XQ922myhwIf3GucujCY',
    appId: '1:586525703658:ios:e5af38feb988a0b396c693',
    messagingSenderId: '586525703658',
    projectId: 'gezayo-2179c',
    storageBucket: 'gezayo-2179c.firebasestorage.app',
    iosBundleId: 'com.example.gezayoApp',
  );
}
